export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'revert',
        'build',
        'ci',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'chat',
        'rag',
        'api',
        'ui',
        'auth',
        'stripe',
        'db',
        'deps',
        'config',
      ],
    ],
    'scope-empty': [1, 'never'],
    'subject-case': [0],
    'body-max-line-length': [0],
  },
};
